branches:
  only:
    - staging
    - trying
    - master
dist: trusty
sudo: false
os:
  - linux
  - osx
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - beta
    - nightly
